Repository Pavithra-ks-06/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#1 create graphicspython
  graphicspython.py
Labels: hacktoberfest-accepted, Hacktoberfest2022, HACKTOBERFEST2022-ACCEPTED

#3 create pingpong
  pingpong.py
Labels: hacktoberfest-accepted, Hacktoberfest2022, HACKTOBERFEST2022-ACCEPTED

#2 shinchan using turtle
  sinchan.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted

#10 Create graphic.py
  graphic.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#12 Create Game.py
  Game.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#11 Create Animation.py
  Animation.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#14 Create BounceBall.py
  BounceBall.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#15 Animal_quiz Program
  Animal_quiz
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#16 added a game in python
  dice_roll.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#18 Created a Random Password generator in Python
  RandomPasswordGenerator.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#27 Added a web scrapper
  web_scrapper.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#28 Added a currency convertor
  currency_convertor.java
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#29 added a sukodu game in python
  sudoku.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#30 added a login form using tkinter in python
  login_form.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#32 Added Digital CLock in python
  DigitalClock.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest

#31 Guess The Number
  guessnum.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest
